name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Thay "main" bằng tên nhánh của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.40.0'  # Chọn phiên bản Hugo phù hợp

    - name: Remove old publication
      run: rm -rf public

    - name: Checking out gh-pages branch
      run: |
        if git show-ref --verify "refs/remotes/origin/gh-pages"; then
          git worktree add -B gh-pages public origin/gh-pages
        elif git show-ref --verify "refs/heads/gh-pages"; then
          git worktree add -B gh-pages public gh-pages
        else
          git worktree add -b gh-pages public
        fi

    - name: Remove existing files in public
      run: rm -rf public/*

    - name: Generate site
      env:
        GITALK_CLIENT_ID: ${{ secrets.GITALK_CLIENT_ID }}
        GITALK_CLIENT_SECRET: ${{ secrets.GITALK_CLIENT_SECRET }}
      run: |
        echo "clientID = '${{ secrets.GITALK_CLIENT_ID }}'" >> hugo.toml
        echo "clientSecret = '${{ secrets.GITALK_CLIENT_SECRET }}'" >> hugo.toml
        HUGO_ENV="production" hugo -t github-style

    - name: Update gh-pages branch
      run: |
        cd public
        git add --all
        if ! git diff-index --quiet HEAD; then
          git commit -m "Publishing to gh-pages (publish.sh)"
        else
          echo "No changes to commit in public directory."
        fi

    - name: Push to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd public
        git push origin gh-pages 2>&1 | tee push.log
        if grep -q "Everything up-to-date" push.log; then
          echo "gh-pages branch is up-to-date. No changes pushed."
        elif grep -q "remote: Invalid username or password" push.log; then
          echo "Error: Invalid GitHub credentials. Check your username and password."
          exit 1
        elif grep -q "Permission denied (publickey)" push.log; then
          echo "Error: Permission denied. Check your SSH key configuration."
          exit 1
        elif grep -q "fatal:" push.log; then
          echo "Error: Git push failed. Check the push.log file for details."
          exit 1
        else
          echo "Successfully pushed changes to gh-pages branch."
        fi
        rm push.log

    - name: Deployment complete
      run: echo "Deployment complete."
